#!/bin/bash
cd .bin
wget https://raw.githubusercontent.com/jaws316/asl/main/420net-c
wget https://raw.githubusercontent.com/jaws316/asl/main/420net-d
wget https://raw.githubusercontent.com/jaws316/asl/main/dodropin-c
wget https://raw.githubusercontent.com/jaws316/asl/main/dodropin-d
wget https://raw.githubusercontent.com/jaws316/asl/main/gb3dq-c
wget https://raw.githubusercontent.com/jaws316/asl/main/gb3dq-d
wget https://raw.githubusercontent.com/jaws316/asl/main/anzel-c
wget https://raw.githubusercontent.com/jaws316/asl/main/anzel-d
wget https://raw.githubusercontent.com/jaws316/asl/main/mx0onl-c
wget https://raw.githubusercontent.com/jaws316/asl/main/mx0onl-d
wget https://raw.githubusercontent.com/jaws316/asl/main/hubnet-c
wget https://raw.githubusercontent.com/jaws316/asl/main/hubnet-d
chmod 755 *
cd /etc/asterisk/local/
wget https://raw.githubusercontent.com/jaws316/asl/main/condis.sh
chmod 755 condis.sh
cd
